spring:
  application:
    name: poc-app
  security:
    oauth2:
      resourceserver:
        jwt:
          # Automatically fetches public keys via OIDC discovery
#          issuer-uri: https://keycloak-yuxian-guo-dev.apps.rm1.0a51.p1.openshiftapps.com/realms/poc-app
           jwk-set-uri: https://keycloak-yuxian-guo-dev.apps.rm1.0a51.p1.openshiftapps.com/realms/poc-app/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
